# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d6e545f12b04aacbaceb241ccd450db366a0a4ae447f647089c9985fd0659f4c6187c2336da15c333f0dbed917b543091a161cb10fce5281813898df297ad2ed

test:
  secret_key_base: f309b11f0588dac83c6008319a0edd6710cd7bfa24f05e9648360749048551dc4d57725c94f430d9bf93ff3c4e543fa340d6e818f69e9dc744629a8e4a9ea40f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
